// Movie metadata type
export interface Movie {
  id: string;
  title: string;
  poster: string;
  backdrop?: string;
  rating: string;
  year: string;
  duration: string;
  genres: string[];
  description: string;
  match: number;
  type: 'movie' | 'tv';
  isNew?: boolean;
}

export const movies: Movie[] = [
  {
    id: '1',
    title: 'Dexter',
    poster: '/posters/dexter.jfif',
    rating: 'TV-MA',
    year: '2006',
    duration: '8 Seasons',
    genres: ['Crime', 'Drama', 'Thriller'],
    description: 'By day, mild-mannered Dexter is a blood-spatter analyst for the Miami police. But at night, he is a serial killer who only targets other murderers.',
    match: 98,
    type: 'tv',
  },
  {
    id: '2',
    title: 'You',
    poster: '/posters/you.jfif',
    rating: 'TV-MA',
    year: '2018',
    duration: '4 Seasons',
    genres: ['Crime', 'Drama', 'Romance'],
    description: 'A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is transfixed by.',
    match: 96,
    type: 'tv',
  },
  {
    id: '3',
    title: 'Suits',
    poster: '/posters/suits.jfif',
    rating: 'TV-14',
    year: '2011',
    duration: '9 Seasons',
    genres: ['Drama', 'Comedy'],
    description: 'On the run from a drug deal gone bad, brilliant college dropout Mike Ross finds himself working with Harvey Specter, one of New York City\'s best lawyers.',
    match: 94,
    type: 'tv',
  },
  {
    id: '4',
    title: 'The Boys',
    poster: '/posters/the-boys.jfif',
    rating: 'TV-MA',
    year: '2019',
    duration: '4 Seasons',
    genres: ['Action', 'Comedy', 'Crime'],
    description: 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.',
    match: 97,
    type: 'tv',
  },
  {
    id: '5',
    title: 'Day of the Jackal',
    poster: '/posters/day-of-jackal.jfif',
    rating: 'TV-MA',
    year: '2024',
    duration: '1 Season',
    genres: ['Crime', 'Drama', 'Thriller'],
    description: 'A ruthless assassin, known as the Jackal, is hired to eliminate a high-profile target, leading to a gripping cat-and-mouse chase across Europe.',
    match: 95,
    type: 'tv',
    isNew: true,
  },
  {
    id: '6',
    title: 'Peaky Blinders',
    poster: '/posters/peaky-blinders.jfif',
    rating: 'TV-MA',
    year: '2013',
    duration: '6 Seasons',
    genres: ['Crime', 'Drama'],
    description: 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps.',
    match: 99,
    type: 'tv',
  },
  {
    id: '7',
    title: 'Knives Out',
    poster: '/posters/knives-out.jfif',
    rating: 'PG-13',
    year: '2019',
    duration: '2h 10m',
    genres: ['Comedy', 'Crime', 'Drama'],
    description: 'A detective investigates the death of a patriarch of an eccentric, combative family.',
    match: 93,
    type: 'movie',
  },
  {
    id: '8',
    title: 'Road House',
    poster: '/posters/road-house.jfif',
    rating: 'R',
    year: '2024',
    duration: '2h 1m',
    genres: ['Action', 'Thriller'],
    description: 'Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.',
    match: 91,
    type: 'movie',
    isNew: true,
  },
  {
    id: '9',
    title: 'Mr. & Mrs. Smith',
    poster: '/posters/mr-mrs-smith.jfif',
    rating: 'TV-MA',
    year: '2024',
    duration: '1 Season',
    genres: ['Action', 'Comedy', 'Drama'],
    description: 'Two strangers land jobs with a spy agency that offers them a life of espionage, wealth, and travel.',
    match: 92,
    type: 'tv',
    isNew: true,
  },
  {
    id: '10',
    title: 'Hit Man',
    poster: '/posters/hit-man.jfif',
    rating: 'R',
    year: '2023',
    duration: '1h 55m',
    genres: ['Comedy', 'Crime', 'Romance'],
    description: 'A professor moonlighting as a hit man of sorts for his city police department descends into dangerous territory.',
    match: 89,
    type: 'movie',
    isNew: true,
  },
  {
    id: '11',
    title: 'Twisters',
    poster: '/posters/twisters.jpg',
    rating: 'PG-13',
    year: '2024',
    duration: '2h 2m',
    genres: ['Action', 'Adventure', 'Thriller'],
    description: 'A retired tornado-chaser and meteorologist is persuaded to return to Oklahoma to work with a new team and new technologies.',
    match: 88,
    type: 'movie',
    isNew: true,
  },
  {
    id: '12',
    title: 'Transformers One',
    poster: '/posters/transformers-one.jpg',
    rating: 'PG',
    year: '2024',
    duration: '1h 44m',
    genres: ['Animation', 'Action', 'Adventure'],
    description: 'The untold origin story of Optimus Prime and Megatron, who were once friends bonded like brothers.',
    match: 90,
    type: 'movie',
    isNew: true,
  },
  {
    id: '13',
    title: 'Super Mario Bros.',
    poster: '/posters/super-mario.jpg',
    rating: 'PG',
    year: '2023',
    duration: '1h 32m',
    genres: ['Animation', 'Adventure', 'Comedy'],
    description: 'A plumber named Mario travels through an underground labyrinth with his brother Luigi, trying to save a captured princess.',
    match: 95,
    type: 'movie',
  },
  {
    id: '14',
    title: 'Sonic 3',
    poster: '/posters/sonic-3.jpg',
    rating: 'PG',
    year: '2024',
    duration: '1h 50m',
    genres: ['Animation', 'Action', 'Adventure'],
    description: 'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious enemy with abilities unlike anything they have faced before.',
    match: 94,
    type: 'movie',
    isNew: true,
  },
  {
    id: '15',
    title: 'A Working Man',
    poster: '/posters/a-working-man.jfif',
    rating: 'R',
    year: '2025',
    duration: '1h 56m',
    genres: ['Action', 'Thriller'],
    description: 'Levon Cade left behind a decorated military career to work in construction, but when his boss\'s daughter disappears, he\'s called on to use his skills.',
    match: 87,
    type: 'movie',
    isNew: true,
  },
  {
    id: '16',
    title: 'Wednesday',
    poster: '/posters/wednesday.jpg',
    rating: 'TV-14',
    year: '2022',
    duration: '1 Season',
    genres: ['Comedy', 'Crime', 'Fantasy'],
    description: 'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.',
    match: 99,
    type: 'tv',
  },
  {
    id: '17',
    title: 'Stranger Things',
    poster: '/posters/stranger-things.jpg',
    backdrop: '/posters/stranger-things-backdrop.png',
    rating: 'TV-14',
    year: '2016',
    duration: '4 Seasons',
    genres: ['Drama', 'Fantasy', 'Horror'],
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    match: 98,
    type: 'tv',
  },
  {
    id: '18',
    title: 'Squid Game',
    poster: '/posters/squid-game.jpg',
    rating: 'TV-MA',
    year: '2021',
    duration: '1 Season',
    genres: ['Action', 'Drama', 'Mystery'],
    description: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
    match: 97,
    type: 'tv',
  },
  {
    id: '19',
    title: 'Bridgerton',
    poster: '/posters/bridgerton.jpg',
    rating: 'TV-MA',
    year: '2020',
    duration: '3 Seasons',
    genres: ['Drama', 'Romance'],
    description: 'The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society. Inspired by Julia Quinn\'s best-selling novels.',
    match: 95,
    type: 'tv',
  },
  {
    id: '20',
    title: 'Reacher',
    poster: '/posters/reacher.jpg',
    rating: 'TV-MA',
    year: '2022',
    duration: '2 Seasons',
    genres: ['Action', 'Crime', 'Drama'],
    description: 'Veteran military police investigator Jack Reacher is falsely accused of murder and finds himself in the middle of a deadly conspiracy.',
    match: 96,
    type: 'tv',
  },
  {
    id: '21',
    title: 'Fallout',
    poster: '/posters/fallout.jpg',
    rating: 'TV-MA',
    year: '2024',
    duration: '1 Season',
    genres: ['Action', 'Adventure', 'Drama'],
    description: 'In a future, post-apocalyptic Los Angeles brought about by nuclear decimation, citizens must live in underground bunkers to protect themselves from radiation, mutants and bandits.',
    match: 94,
    type: 'tv',
    isNew: true,
  },
  {
    id: '22',
    title: 'The Terminal List',
    poster: '/posters/terminal-list.jpg',
    rating: 'TV-MA',
    year: '2022',
    duration: '1 Season',
    genres: ['Action', 'Drama', 'Thriller'],
    description: 'A former Navy SEAL officer investigates why his entire platoon was ambushed during a high-stakes covert mission.',
    match: 92,
    type: 'tv',
  },
  {
    id: '23',
    title: 'Rings of Power',
    poster: '/posters/rings-of-power.jpg',
    rating: 'TV-14',
    year: '2022',
    duration: '2 Seasons',
    genres: ['Action', 'Adventure', 'Drama'],
    description: 'Epic drama set thousands of years before the events of J.R.R. Tolkien\'s \'The Hobbit\' and \'The Lord of the Rings\'.',
    match: 91,
    type: 'tv',
  },
  {
    id: '24',
    title: 'Carry-On',
    poster: '/posters/carry-on.jpg',
    rating: 'PG-13',
    year: '2024',
    duration: '1h 59m',
    genres: ['Action', 'Thriller'],
    description: 'A mysterious traveler blackmails a young TSA agent to let a dangerous package slip through on Christmas Eve.',
    match: 89,
    type: 'movie',
    isNew: true,
  },
  {
    id: '25',
    title: 'Damsel',
    poster: '/posters/damsel.jpg',
    rating: 'PG-13',
    year: '2024',
    duration: '1h 48m',
    genres: ['Adventure', 'Fantasy'],
    description: 'A dutiful damsel agrees to marry a handsome prince, only to find the royal family has recruited her as a sacrifice to repay an ancient debt.',
    match: 88,
    type: 'movie',
    isNew: true,
  },
  {
    id: '26',
    title: 'Back in Action',
    poster: '/posters/back-in-action.jpg',
    rating: 'PG-13',
    year: '2025',
    duration: '2h 10m',
    genres: ['Action', 'Comedy'],
    description: 'Years after giving up life as CIA spies to start a family, Emily and Matt find themselves pulled back into the world of espionage when their cover is blown.',
    match: 90,
    type: 'movie',
    isNew: true,
  },
  {
    id: '27',
    title: 'The Fall Guy',
    poster: '/posters/fall-guy.jpg',
    rating: 'PG-13',
    year: '2024',
    duration: '2h 6m',
    genres: ['Action', 'Comedy'],
    description: 'A stuntman, fresh off an almost career-ending accident, has to track down a missing movie star, solve a conspiracy and try to win back the love of his life.',
    match: 93,
    type: 'movie',
    isNew: true,
  },
  {
    id: '28',
    title: 'Alien: Romulus',
    poster: '/posters/alien-romulus.jpg',
    rating: 'R',
    year: '2024',
    duration: '1h 59m',
    genres: ['Horror', 'Sci-Fi'],
    description: 'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
    match: 94,
    type: 'movie',
    isNew: true,
  },
  {
    id: '29',
    title: 'Conclave',
    poster: '/posters/conclave.jpg',
    rating: 'PG-13',
    year: '2024',
    duration: '2h 0m',
    genres: ['Drama', 'Thriller'],
    description: 'Cardinal Lawrence is tasked with leading one of the world\'s most secretive and ancient events, selecting a new Pope, where he finds himself at the center of a conspiracy.',
    match: 87,
    type: 'movie',
    isNew: true,
  },
  {
    id: '30',
    title: 'Nosferatu',
    poster: '/posters/nosferatu.jpg',
    rating: 'R',
    year: '2024',
    duration: '2h 12m',
    genres: ['Fantasy', 'Horror'],
    description: 'A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.',
    match: 92,
    type: 'movie',
    isNew: true,
  },
  {
    id: '31',
    title: 'Oppenheimer',
    poster: '/posters/oppenheimer.jpg',
    rating: 'R',
    year: '2023',
    duration: '3h 0m',
    genres: ['Biography', 'Drama', 'History'],
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    match: 98,
    type: 'movie',
  },
  {
    id: '32',
    title: 'Dune: Part Two',
    poster: '/posters/dune-2.jpg',
    rating: 'PG-13',
    year: '2024',
    duration: '2h 46m',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    description: 'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
    match: 99,
    type: 'movie',
    isNew: true,
  },
  {
    id: '33',
    title: 'Killers of the Flower Moon',
    poster: '/posters/killers-flower-moon.jpg',
    rating: 'R',
    year: '2023',
    duration: '3h 26m',
    genres: ['Crime', 'Drama', 'History'],
    description: 'Real-life members of the Osage Nation in the United States are murdered under mysterious circumstances in the 1920s, sparking a major F.B.I. investigation.',
    match: 91,
    type: 'movie',
  },
  {
    id: '34',
    title: 'Poor Things',
    poster: '/posters/poor-things.jpg',
    rating: 'R',
    year: '2023',
    duration: '2h 21m',
    genres: ['Comedy', 'Drama', 'Romance'],
    description: 'The incredible tale and fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.',
    match: 89,
    type: 'movie',
  },
  {
    id: '35',
    title: 'The Idea of You',
    poster: '/posters/idea-of-you.jpg',
    rating: 'R',
    year: '2024',
    duration: '1h 55m',
    genres: ['Comedy', 'Drama', 'Romance'],
    description: 'Solène, a 40-year-old single mother, begins an unexpected romance with 24-year-old Hayes Campbell, the lead singer of August Moon, the hottest boy band on the planet.',
    match: 86,
    type: 'movie',
    isNew: true,
  },
  {
    id: '36',
    title: 'Gladiator II',
    poster: '/posters/gladiator-2.jpg',
    rating: 'R',
    year: '2024',
    duration: '2h 30m',
    genres: ['Action', 'Adventure', 'Drama'],
    description: 'After his home is conquered by the tyrannical emperors who now lead Rome, Lucius is forced to enter the Colosseum and must look to his past to find strength.',
    match: 94,
    type: 'movie',
    isNew: true,
  },
  {
    id: '37',
    title: 'Moana 2',
    poster: '/posters/moana-2.jpg',
    rating: 'PG',
    year: '2024',
    duration: '1h 40m',
    genres: ['Animation', 'Adventure', 'Comedy'],
    description: 'After receiving an unexpected call from her wayfinding ancestors, Moana must journey to the far seas of Oceania and into dangerous, long-lost waters.',
    match: 95,
    type: 'movie',
    isNew: true,
  },
  {
    id: '38',
    title: 'Inside Out 2',
    poster: '/posters/inside-out-2.jpg',
    rating: 'PG',
    year: '2024',
    duration: '1h 36m',
    genres: ['Animation', 'Adventure', 'Comedy'],
    description: 'Follow Riley, in her teenage years, encountering new emotions.',
    match: 97,
    type: 'movie',
    isNew: true,
  },
  {
    id: '39',
    title: 'Deadpool & Wolverine',
    poster: '/posters/deadpool-wolverine.jpg',
    rating: 'R',
    year: '2024',
    duration: '2h 7m',
    genres: ['Action', 'Comedy', 'Sci-Fi'],
    description: 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up.',
    match: 98,
    type: 'movie',
    isNew: true,
  },
  {
    id: '40',
    title: 'Wicked',
    poster: '/posters/wicked.jpg',
    rating: 'PG',
    year: '2024',
    duration: '2h 40m',
    genres: ['Fantasy', 'Musical', 'Romance'],
    description: 'The story of how a green-skinned woman framed by the Wizard of Oz becomes the Wicked Witch of the West.',
    match: 94,
    type: 'movie',
    isNew: true,
  },
  {
    id: '41',
    title: 'Black Mirror',
    poster: '/posters/black-mirror.jpg',
    rating: 'TV-MA',
    year: '2011',
    duration: '6 Seasons',
    genres: ['Drama', 'Sci-Fi', 'Thriller'],
    description: 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.',
    match: 96,
    type: 'tv',
  },
  {
    id: '42',
    title: 'The Witcher',
    poster: '/posters/the-witcher.jpg',
    rating: 'TV-MA',
    year: '2019',
    duration: '3 Seasons',
    genres: ['Action', 'Adventure', 'Drama'],
    description: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
    match: 93,
    type: 'tv',
  },
  {
    id: '43',
    title: 'Yellowstone',
    poster: '/posters/yellowstone.jpg',
    rating: 'TV-MA',
    year: '2018',
    duration: '5 Seasons',
    genres: ['Drama', 'Western'],
    description: 'A ranching family in Montana faces off against others encroaching on their land.',
    match: 95,
    type: 'tv',
  },
  {
    id: '44',
    title: 'The Last of Us',
    poster: '/posters/last-of-us.jpg',
    rating: 'TV-MA',
    year: '2023',
    duration: '1 Season',
    genres: ['Action', 'Adventure', 'Drama'],
    description: 'After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity\'s last hope.',
    match: 99,
    type: 'tv',
  },
  {
    id: '45',
    title: 'House of the Dragon',
    poster: '/posters/house-of-dragon.jpg',
    rating: 'TV-MA',
    year: '2022',
    duration: '2 Seasons',
    genres: ['Action', 'Adventure', 'Drama'],
    description: 'The story of the Targaryen civil war that took place about 200 years before events portrayed in Game of Thrones.',
    match: 98,
    type: 'tv',
  },
  // --- 20 NEW ENTRIES ---
  {
    id: '46',
    title: 'The Batman',
    poster: '/posters/the-batman.jpg',
    rating: 'PG-13',
    year: '2022',
    duration: '2h 56m',
    genres: ['Action', 'Crime', 'Drama'],
    description: 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city\'s hidden corruption.',
    match: 95,
    type: 'movie',
  },
  {
    id: '47',
    title: 'Breaking Bad',
    poster: '/posters/breaking-bad.jpg',
    rating: 'TV-MA',
    year: '2008',
    duration: '5 Seasons',
    genres: ['Crime', 'Drama', 'Thriller'],
    description: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family\'s future.',
    match: 99,
    type: 'tv',
  },
  {
    id: '48',
    title: 'The Sopranos',
    poster: '/posters/sopranos.jpg',
    rating: 'TV-MA',
    year: '1999',
    duration: '6 Seasons',
    genres: ['Crime', 'Drama'],
    description: 'New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state, leading him to seek professional psychiatric counseling.',
    match: 97,
    type: 'tv',
  },
  {
    id: '49',
    title: 'Succession',
    poster: '/posters/succession.jpg',
    rating: 'TV-MA',
    year: '2018',
    duration: '4 Seasons',
    genres: ['Drama', 'Comedy'],
    description: 'The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down from the company.',
    match: 96,
    type: 'tv',
  },
  {
    id: '50',
    title: 'Avatar: The Way of Water',
    poster: '/posters/avatar-2.jpg',
    rating: 'PG-13',
    year: '2022',
    duration: '3h 12m',
    genres: ['Action', 'Adventure', 'Fantasy'],
    description: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri.',
    match: 91,
    type: 'movie',
  },
  {
    id: '51',
    title: 'Top Gun: Maverick',
    poster: '/posters/top-gun-maverick.jpg',
    rating: 'PG-13',
    year: '2022',
    duration: '2h 10m',
    genres: ['Action', 'Drama'],
    description: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN\'s elite graduates on a mission.',
    match: 98,
    type: 'movie',
  },
  {
    id: '52',
    title: 'The White Lotus',
    poster: '/posters/white-lotus.jpg',
    rating: 'TV-MA',
    year: '2021',
    duration: '2 Seasons',
    genres: ['Comedy', 'Drama'],
    description: 'The exploits of various guests and employees at a tropical resort over the span of a week.',
    match: 93,
    type: 'tv',
  },
  {
    id: '53',
    title: 'The Bear',
    poster: '/posters/the-bear.jpg',
    rating: 'TV-MA',
    year: '2022',
    duration: '2 Seasons',
    genres: ['Comedy', 'Drama'],
    description: 'A young chef from the fine dining world returns to Chicago to run his family\'s sandwich shop.',
    match: 95,
    type: 'tv',
    isNew: true,
  },
  {
    id: '54',
    title: 'Dune',
    poster: '/posters/dune.jpg',
    rating: 'PG-13',
    year: '2021',
    duration: '2h 35m',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    description: 'A noble family becomes embroiled in a war for control over the galaxy\'s most valuable asset while its heir becomes troubled by visions of a dark future.',
    match: 93,
    type: 'movie',
  },
  {
    id: '55',
    title: 'The Matrix',
    poster: '/posters/matrix.jpg',
    rating: 'R',
    year: '1999',
    duration: '2h 16m',
    genres: ['Action', 'Sci-Fi'],
    description: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth—the life he knows is the elaborate deception of an evil cyber-intelligence.',
    match: 96,
    type: 'movie',
  },
  {
    id: '56',
    title: 'Inception',
    poster: '/posters/inception.jpg',
    rating: 'PG-13',
    year: '2010',
    duration: '2h 28m',
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    match: 97,
    type: 'movie',
  },
  {
    id: '57',
    title: 'Shogun',
    poster: '/posters/shogun.jpg',
    rating: 'TV-MA',
    year: '2024',
    duration: '1 Season',
    genres: ['Adventure', 'Drama', 'History'],
    description: 'When a mysterious European ship is found marooned in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power and devastate his enemies.',
    match: 97,
    type: 'tv',
    isNew: true,
  },
  {
    id: '58',
    title: 'Spider-Man: Across the Spider-Verse',
    poster: '/posters/spider-verse.jpg',
    rating: 'PG',
    year: '2023',
    duration: '2h 20m',
    genres: ['Animation', 'Action', 'Adventure'],
    description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
    match: 96,
    type: 'movie',
  },
  {
    id: '59',
    title: 'Everything Everywhere All at Once',
    poster: '/posters/eeaao.jpg',
    rating: 'R',
    year: '2022',
    duration: '2h 19m',
    genres: ['Action', 'Adventure', 'Comedy'],
    description: 'A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.',
    match: 94,
    type: 'movie',
  },
  {
    id: '60',
    title: 'Beef',
    poster: '/posters/beef.jpg',
    rating: 'TV-MA',
    year: '2023',
    duration: '1 Season',
    genres: ['Comedy', 'Drama'],
    description: 'Two people let a road rage incident burrow into their minds and slowly consume their every thought and action.',
    match: 92,
    type: 'tv',
  },
  {
    id: '61',
    title: 'The Penguin',
    poster: '/posters/penguin.jpg',
    rating: 'TV-MA',
    year: '2024',
    duration: '1 Season',
    genres: ['Crime', 'Drama'],
    description: 'Following the events of The Batman, Oz Cobb makes a play to seize the reins of the crime world in Gotham.',
    match: 95,
    type: 'tv',
    isNew: true,
  },
  {
    id: '62',
    title: 'Arcane',
    poster: '/posters/arcane.jpg',
    rating: 'TV-14',
    year: '2021',
    duration: '2 Seasons',
    genres: ['Animation', 'Action', 'Adventure'],
    description: 'Set in Utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart.',
    match: 98,
    type: 'tv',
    isNew: true, // Specifically referencing Season 2
  },
  {
    id: '63',
    title: 'Civil War',
    poster: '/posters/civil-war.jpg',
    rating: 'R',
    year: '2024',
    duration: '1h 49m',
    genres: ['Action', 'Thriller'],
    description: 'A journey across a dystopian future America, following a team of military-embedded journalists as they race against time to reach DC before rebel factions descend upon the White House.',
    match: 86,
    type: 'movie',
    isNew: true,
  },
  {
    id: '64',
    title: 'Furiosa: A Mad Max Saga',
    poster: '/posters/furiosa.jpg',
    rating: 'R',
    year: '2024',
    duration: '2h 28m',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    description: 'The origin story of renegade warrior Furiosa before her encounter and teamup with Mad Max.',
    match: 89,
    type: 'movie',
    isNew: true,
  },
  {
    id: '65',
    title: 'The Substance',
    poster: '/posters/substance.jpg',
    rating: 'R',
    year: '2024',
    duration: '2h 21m',
    genres: ['Drama', 'Horror'],
    description: 'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
    match: 90,
    type: 'movie',
    isNew: true,
  },
  {
    id: '66',
    title: 'Gangs of London',
    poster: '/posters/gangs-of-london.jfif',
    rating: 'TV-MA',
    year: '2020',
    duration: '2 Seasons',
    genres: ['Action', 'Crime', 'Drama'],
    description: 'When the head of a criminal organization is assassinated, the sudden power vacuum threatens the fragile peace between the international gangs of London.',
    match: 94,
    type: 'tv',
  }
];

// --- Existing Home Page Categories ---
export const initialCategories = [
  { id: 'trending', title: 'Trending Now', movies: [movies[45], movies[46], movies[17], movies[60], movies[56], movies[38], movies[65], movies[43], movies[0], movies[5]] },
  { id: 'continue', title: 'Continue Watching', movies: [movies[2], movies[47], movies[48], movies[52], movies[41], movies[7], movies[20], movies[9]] },
  { id: 'new', title: 'New Releases', movies: [movies[62], movies[63], movies[64], movies[65], movies[39], movies[37], movies[27], movies[23], movies[35]] },
  { id: 'family', title: 'Family Favorites', movies: [movies[12], movies[13], movies[57], movies[37], movies[36], movies[49], movies[11]] },
  { id: 'action', title: 'Action & Adventure', movies: [movies[45], movies[50], movies[54], movies[55], movies[58], movies[63], movies[31], movies[44], movies[65]] },
  { id: 'drama', title: 'Critics\' Choice', movies: [movies[48], movies[49], movies[51], movies[52], movies[53], movies[59], movies[18], movies[2]] },
  { id: 'shows', title: 'Top Rated Shows', movies: [movies[46], movies[47], movies[52], movies[56], movies[61], movies[65], movies[16], movies[42]] },
  { id: 'awards', title: 'Award Winning Pieces', movies: [movies[58], movies[55], movies[30], movies[32], movies[28], movies[6], movies[50]] },
];

// --- Dedicated TV Show Categories ---
export const tvCategories = [
  { id: 'tv-action', title: 'Action TV Thrillers', movies: movies.filter(m => m.type === 'tv' && m.genres.includes('Action')) },
  { id: 'tv-drama', title: 'Award-Winning TV Dramas', movies: movies.filter(m => m.type === 'tv' && m.genres.includes('Drama')) },
  { id: 'tv-comedy', title: 'TV Comedies', movies: movies.filter(m => m.type === 'tv' && m.genres.includes('Comedy')) },
  { id: 'tv-crime', title: 'Crime & Investigation', movies: movies.filter(m => m.type === 'tv' && m.genres.includes('Crime')) },
];

// --- Dedicated Movie Categories ---
export const movieCategories = [
  { id: 'movie-action', title: 'High-Octane Action', movies: movies.filter(m => m.type === 'movie' && m.genres.includes('Action')) },
  { id: 'movie-sci-fi', title: 'Sci-Fi & Fantasy', movies: movies.filter(m => m.type === 'movie' && m.genres.some(g => g === 'Sci-Fi' || g === 'Fantasy')) },
  { id: 'movie-comedy', title: 'Laugh Out Loud Comedies', movies: movies.filter(m => m.type === 'movie' && m.genres.includes('Comedy')) },
  { id: 'movie-drama', title: 'Critically Acclaimed Dramas', movies: movies.filter(m => m.type === 'movie' && m.genres.includes('Drama')) },
  { id: 'movie-animation', title: 'Fun for the Family', movies: movies.filter(m => m.type === 'movie' && m.genres.includes('Animation')) },
];

// --- Dedicated New & Popular Categories ---
export const newAndPopularCategories = [
  { id: 'new-movies', title: 'Fresh Movies Just Added', movies: movies.filter(m => m.type === 'movie' && m.isNew) },
  { id: 'new-shows', title: 'Latest TV Show Drops', movies: movies.filter(m => m.type === 'tv' && m.isNew) },
  { id: 'popular-all', title: 'Global Top 10 Today', movies: [...movies].sort((a, b) => b.match - a.match).slice(0, 10) },
];
